name: 'iptest-proxyip '

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  schedule:
   - cron: '0 */8 * * *'
jobs:
  ddy:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: 'Set up Python'
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.x
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        # timeout-minutes: 360
        run: |
          mv *.csv oldcsv/
          wget -O IPDBproxy.txt  https://raw.githubusercontent.com/ymyuuu/IPDB/main/proxy.txt
          cp raw_ip.txt ip.txt 
          cat IPDBproxy.txt >> ip.txt 
          mv IPDBproxy.txt oldrealip/IPDBproxy-$(date +%Y%m%d%H%M%S).txt
          chmod +x ./iptest.sh
          bash ./iptest.sh -t 100
          python
          #####################################################################################
          import pandas as pd
          # 读取CSV文件
          df = pd.read_csv('latest.csv')
       
          # 创建一个新的列，其中包含"峰值速度"列的值，但是已经去掉了单位（kB/s）
          df['峰值速度数值'] = df['峰值速度'].str.replace(' kB/s', '').astype(float)
       
          # 按照"峰值速度数值"列的值进行排序
          df_sorted = df.sort_values(by='峰值速度数值', ascending=False)
       
          #df_gj = df_sorted[df_sorted['国家'] == 'US']
       
          # 将排序后的DataFrame保存回CSV文件
          df_sorted.to_csv('latest_sorted.csv', index=False)
          #####################################################################################          
          import pandas as pd
          # 读取 CSV 文件
          df = pd.read_csv('latest_sorted.csv')
          
          # 提取第一列数据
          first_column = df.iloc[:15, 0]
          
          # 将数据写入文本文件
          first_column.to_csv('proxyip.txt', index=False, header=False)
          #####################################################################################
          exit()          
          mv realip*.txt oldrealip/
          rm -rf ip.txt
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "⌚️$(date +%Y%m%d%H%M%S)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          # github_token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
